version: "3"

services:
  db:
    image: openmaptiles/postgis-preloaded
    ports:
      - "5432:5432"

  tools:
    image: openmaptiles/openmaptiles-tools
    volumes:
      - ./tiles:/tileset
      - ./data:/import
